"""empty message

Revision ID: 004f3ec2f687
Revises: 9ea61e7f8a2a
Create Date: 2021-03-20 18:38:29.000967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '004f3ec2f687'
down_revision = '9ea61e7f8a2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_token', sa.Column('api_type', sa.SmallInteger(), nullable=False))
    op.add_column('api_token', sa.Column('status', sa.Boolean(), nullable=False))
    op.drop_column('api_token', 'status1')
    op.drop_column('api_token', 'api_type1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_token', sa.Column('api_type1', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False))
    op.add_column('api_token', sa.Column('status1', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('api_token', 'status')
    op.drop_column('api_token', 'api_type')
    # ### end Alembic commands ###
