"""empty message

Revision ID: 4b4fa91b6679
Revises: 68f22ccc7f9d
Create Date: 2021-03-21 21:52:49.633966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b4fa91b6679'
down_revision = '68f22ccc7f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_log', sa.Column('message', sa.String(length=100), nullable=True))
    op.add_column('base_log', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_log', 'status')
    op.drop_column('base_log', 'message')
    # ### end Alembic commands ###
