"""empty message

Revision ID: 5ff22e92027e
Revises: 44292c0acba2
Create Date: 2021-03-21 20:42:48.870549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ff22e92027e'
down_revision = '44292c0acba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_log', sa.Column('args', sa.String(length=256), nullable=False))
    op.add_column('base_log', sa.Column('base_customer1', sa.Integer(), nullable=False))
    op.add_column('base_log', sa.Column('params', sa.String(length=256), nullable=False))
    op.add_column('base_log', sa.Column('result', sa.String(length=256), nullable=False))
    op.drop_column('base_log', 'base_customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_log', sa.Column('base_customer', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=False))
    op.drop_column('base_log', 'result')
    op.drop_column('base_log', 'params')
    op.drop_column('base_log', 'base_customer1')
    op.drop_column('base_log', 'args')
    # ### end Alembic commands ###
