"""empty message

Revision ID: 68f22ccc7f9d
Revises: c943a4551c7a
Create Date: 2021-03-21 20:48:11.717009

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68f22ccc7f9d'
down_revision = 'c943a4551c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_log', sa.Column('model_id', sa.Integer(), nullable=False))
    op.drop_column('base_log', 'model_id1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_log', sa.Column('model_id1', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('base_log', 'model_id')
    # ### end Alembic commands ###
