"""empty message

Revision ID: 739a3343e8b7
Revises: 
Create Date: 2021-03-19 22:56:54.034117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '739a3343e8b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('base_customer', sa.String(length=128), nullable=False),
    sa.Column('apit_token', sa.String(length=128), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apit_token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_token')
    # ### end Alembic commands ###
