"""empty message

Revision ID: 8e38e42f2460
Revises: 8708c7845345
Create Date: 2021-03-23 00:44:50.448320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e38e42f2460'
down_revision = '8708c7845345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_log', sa.Column('route', sa.String(length=100), nullable=True))
    op.alter_column('base_log', 'function',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
    op.alter_column('base_log', 'model_class',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
    op.alter_column('base_log', 'model_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('base_log', 'operation',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('base_log', 'operation',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               nullable=False)
    op.alter_column('base_log', 'model_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('base_log', 'model_class',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
    op.alter_column('base_log', 'function',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
    op.drop_column('base_log', 'route')
    # ### end Alembic commands ###
