"""empty message

Revision ID: 995cd8cb776e
Revises: fecd3b51e7e4
Create Date: 2021-03-20 18:34:11.172091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '995cd8cb776e'
down_revision = 'fecd3b51e7e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_user', sa.Column('code1', sa.Integer(), nullable=False))
    op.add_column('api_user', sa.Column('date1', sa.Date(), nullable=False))
    op.add_column('api_user', sa.Column('email1', sa.String(length=256), nullable=False))
    op.add_column('api_user', sa.Column('score1', sa.Integer(), nullable=False))
    op.add_column('api_user', sa.Column('status1', sa.Boolean(), nullable=False))
    op.drop_column('api_user', 'date')
    op.drop_column('api_user', 'email')
    op.drop_column('api_user', 'status')
    op.drop_column('api_user', 'code')
    op.drop_column('api_user', 'score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_user', sa.Column('score', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=False))
    op.add_column('api_user', sa.Column('code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=False))
    op.add_column('api_user', sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False))
    op.add_column('api_user', sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=False))
    op.add_column('api_user', sa.Column('date', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=False))
    op.drop_column('api_user', 'status1')
    op.drop_column('api_user', 'score1')
    op.drop_column('api_user', 'email1')
    op.drop_column('api_user', 'date1')
    op.drop_column('api_user', 'code1')
    # ### end Alembic commands ###
