"""empty message

Revision ID: 9ea61e7f8a2a
Revises: fe67ce94b866
Create Date: 2021-03-20 18:36:39.772983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ea61e7f8a2a'
down_revision = 'fe67ce94b866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_token', sa.Column('api_type1', sa.SmallInteger(), nullable=False))
    op.add_column('api_token', sa.Column('status1', sa.Boolean(), nullable=False))
    op.drop_column('api_token', 'status')
    op.drop_column('api_token', 'api_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_token', sa.Column('api_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False))
    op.add_column('api_token', sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False))
    op.drop_column('api_token', 'status1')
    op.drop_column('api_token', 'api_type1')
    # ### end Alembic commands ###
