"""empty message

Revision ID: c943a4551c7a
Revises: 5ff22e92027e
Create Date: 2021-03-21 20:47:19.575572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c943a4551c7a'
down_revision = '5ff22e92027e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_log', sa.Column('base_customer', sa.Integer(), nullable=False))
    op.add_column('base_log', sa.Column('model_id1', sa.Integer(), nullable=False))
    op.alter_column('base_log', 'args',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256),
               nullable=True)
    op.alter_column('base_log', 'params',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256),
               nullable=True)
    op.alter_column('base_log', 'result',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256),
               nullable=True)
    op.alter_column('base_log', 'user_email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    op.alter_column('base_log', 'user_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    op.drop_column('base_log', 'base_customer1')
    op.drop_column('base_log', 'model_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_log', sa.Column('model_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False))
    op.add_column('base_log', sa.Column('base_customer1', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.alter_column('base_log', 'user_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    op.alter_column('base_log', 'user_email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    op.alter_column('base_log', 'result',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256),
               nullable=False)
    op.alter_column('base_log', 'params',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256),
               nullable=False)
    op.alter_column('base_log', 'args',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256),
               nullable=False)
    op.drop_column('base_log', 'model_id1')
    op.drop_column('base_log', 'base_customer')
    # ### end Alembic commands ###
