"""empty message

Revision ID: f7d3a34be13b
Revises: 77ed80eda3ad
Create Date: 2021-04-03 05:29:22.365777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7d3a34be13b'
down_revision = '77ed80eda3ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'base_error', 'base_customer', ['base_customer'], ['id'])
    op.alter_column('base_log', 'base_customer',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_foreign_key(None, 'base_log', 'base_customer', ['base_customer'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'base_log', type_='foreignkey')
    op.alter_column('base_log', 'base_customer',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint(None, 'base_error', type_='foreignkey')
    # ### end Alembic commands ###
