"""empty message

Revision ID: fe67ce94b866
Revises: 995cd8cb776e
Create Date: 2021-03-20 18:35:18.359529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe67ce94b866'
down_revision = '995cd8cb776e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_user', sa.Column('code', sa.Integer(), nullable=False))
    op.add_column('api_user', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('api_user', sa.Column('email', sa.String(length=256), nullable=False))
    op.add_column('api_user', sa.Column('score', sa.Integer(), nullable=False))
    op.add_column('api_user', sa.Column('status', sa.Boolean(), nullable=False))
    op.drop_column('api_user', 'email1')
    op.drop_column('api_user', 'date1')
    op.drop_column('api_user', 'score1')
    op.drop_column('api_user', 'status1')
    op.drop_column('api_user', 'code1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_user', sa.Column('code1', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('api_user', sa.Column('status1', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('api_user', sa.Column('score1', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('api_user', sa.Column('date1', sa.DATE(), nullable=False))
    op.add_column('api_user', sa.Column('email1', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=False))
    op.drop_column('api_user', 'status')
    op.drop_column('api_user', 'score')
    op.drop_column('api_user', 'email')
    op.drop_column('api_user', 'date')
    op.drop_column('api_user', 'code')
    # ### end Alembic commands ###
